 version: '3.8'
 services:

  postgres-server:
   image: postgres:latest
   restart: always
   environment:
    POSTGRES_USER: zabbix
    POSTGRES_PASSWORD: zabbix
    POSTGRES_DB: zabbix
    PG_DATA: /var/lib/postgresql/data/pgdata

  zabbix-server:
   image: zabbix/zabbix-server-pgsql:ubuntu-latest
   restart: always
   environment:
    POSTGRES_USER: zabbix
    POSTGRES_PASSWORD: zabbix
    POSTGRES_DB: zabbix
    ZBX_JAVAGATEWAY_ENABLE: "true"
    ZBX_JAVAGATEWAY: zabbix-java-gateway
    ZBX_JAVAGATEWAYPORT: 10052
    ZBX_STARTJAVAPOLLERS: 5
   depends_on:
    - postgres-server
   volumes:
    - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts

  zabbix-web:
   image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
   restart: always
   environment:
    POSTGRES_USER: zabbix
    POSTGRES_PASSWORD: zabbix
    POSTGRES_DB: zabbix
    ZBX_SERVER_HOST: zabbix-server
   depends_on:
    - postgres-server
    - zabbix-server
   ports:
    - 8090:8080

  zabbix-agent:
   image: zabbix/zabbix-agent:latest
   privileged: true
   restart: unless-stopped
   network_mode: "host"
   environment:
    ZBX_SERVER_HOST: 127.0.0.1

  zabbix-java-gateway:
   image: zabbix/zabbix-java-gateway:ubuntu-latest
   ports:
    - 10052:10052
